<a href="https://colab.research.google.com/github/Aryamaan23/ML-TOOLBOX/blob/master/Copy_of_Copy_of_Copy_of_Copy_of_Quiz_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##1

###Q. Generate Random points
Write a function that takes parameters $r_1$, $r_2$, $n$ and generates random points $(x_1, x_2)$ as follows - 
- $n$ random points that lie within a circle with center at $(0, 0)$ and radius $r_1$ $\rightarrow$ These points belong to class ```'inner'```
- $n$ random points that lie outside circle with center at $(0, 0)$ and radius $r_1$ but inside circle with center at $(0, 0)$ and radius $r_2$ $\rightarrow$ These points belong to class ```'outer'```

The function gen_random should return $X$, $Cls$ :
- $X$ is a numpy array of shape $(2n, 2)$ which has the $2n$ random points generated as above
- $Cls$ is a numpy array of shape $(2n,)$ which contains the value of the class corresponding to each point in $X$ (values will be either ```'inner'``` or ```'outer'```)

In [ ]:
import numpy as np
import random as rand
def gen_random_points(r1, r2, n):
  """
  Inputs:
    r1 : float
    r2 : float
    n : int, number of points
  Outputs:
    X : numpy array, shape -> (2n, 2)
    Cls : numpy array, shape -> (2n, )
  """
  ns=np.random.rand(n)*r1
  thetas=np.random.rand(n)*2*np.pi
  x1_s=rs*np.cos(thetas)
  x2_s=rs*np.sin(thetas)

  rs_outer=np.random.rand(n)*(r2-r1)+r1
  thetas_outer=np.random.rand(n)*2*np.pi
  x_1s_outer=rs_outer*np.cos(thetas_outer)
  x_2s_outer=rs_outer*np.sin(thetas_outer)

  X_inner=np.hstack([x_1s.reshape(n,1),x_2s.reshape(n,1)])
  X_outer=np.hstack([x_1s_outer.reshape(n,1),x_2s_outer.reshape(n,1)])
  X=np.vstack([X_inner,X_outer])
  Cls=np.array(['inner']*n+['outer']*n)
  return (X,Cls)

##2

###Q. One-hot encode
Write a function that takes a numpy array $Cls$ of shape $(n, )$ which contains class labels of $n$ samples of data and creates a numpy array, $Y_d$ of shape $(n, \text{unique})$ containing 1-hot representations of the $n$ samples. Here $\text{unique}$ is the number of unique classes in $Cls$. <br>
The function should return two values - 
- $Y_d$ - numpy array of shape $(n, \text{unique})$ with 1-hot representations
- ```cls_order``` - numpy array of shape $(\text{unique}, )$ which contains the labels of the classes in the order in which they occur in the 1-hot representation.


In [ ]:

def one_hot_encode(Cls):
  """
  Inputs:
    Cls: numpy array, shape: (n, ) contains class labels of n data samples
  Outputs:
    Yd : numpy array of shape (n, unique)
    cls_order: numpy array of shape(unique, )
  """
  ### Write your code here
  unique_classes=np.unique(Cls)
  n=Cls.shape[0]
  N=unique_classes.shape[0]
  class_dict={}
  for i in range(N):
    class_dict[unique_classes[i]]=i

  Yd=np.zeros((n,N))
  for i in range(n):
    Yd[i,class_dict[Cls[i]]]=1
  return Yd,unique_classes

In [ ]:
Cls=np.array(['cat','dog','cat','cat','dog'])
one_hot_encode(Cls)

(array([[1., 0.],
        [0., 1.],
        [1., 0.],
        [1., 0.],
        [0., 1.]]), array(['cat', 'dog'], dtype='<U3'))

##3

###Q. Softmax
Write a function that takes a vector (numpy array of shape $(f,)$) - $(y_{in})$ and returns the result vector (numpy array of shape $(f,)$) - $(y_{out})$ of applying the softmax non-linearity to it. <br>
$$
y_{out}^{i} = \frac{e^{y_{in}^{i}}}{\sum_{i=1}^{f}e^{y_{in}^{i}}}
$$ 

where $y^{i}$ refers to the $i^{th}$ component of vector $y$

In [ ]:
def softmax1(y_in):
  """
  Inputs:
    y_in : numpy array of shape (f, ), input vector 
  Outputs:
    y_out : numpy array of shape(f, ), output vector
  """
  ### Write your code here
  e_y_in=(np.e)**y_in
  y_out=e_y_in/np.sum(e_y_in)
  return y_out
  

In [ ]:
a=np.array([1,2,3])
2**a

array([2, 4, 8])

##4

###Q. Standardize
Write a function that takes input dataset $X$ of shape $(n, f)$ and returns dataset $X_{stdz}$  after standardizing $X$ where
$$
  X_{stdz}^i = \frac{X^i - \mu(X)}{\sigma(X)}
$$
where $\mu(X)$ is the feature-wise mean of all samples in $X$ and $\sigma(X)$ is feature-wise standard deviation of all samples in $X$

In [ ]:
from sklearn import preprocessing
import pandas as pd
import numpy as np
def standardize(X):
  """
  Inputs:
    X: numpy array of shape (n, f)
  Outputs:
    X_stdz : numpy array of shape (n, f)
  """
  mu_X=np.mean(X,axis=0)
  sigma_X=np.std(X,axis=0)
  X_stdz=(X-mu_X)/(sigma_x+10**-8)
  return X_stdz

##5

###Q. Normalize
Write a function that takes input dataset $X$ of shape $(n, f)$ and returns dataset $X_{normd}$  after normalizing $X$ where
$$
  X_{normd}^i = \frac{X^i - \min(X)}{max(X) - min(X)}
$$
where $\max(X)$ is the feature-wise maximum of all samples in $X$ and $min(X)$ is feature-wise minimum of all samples in $X$

In [ ]:
from sklearn import preprocessing
import numpy as np
def normalize(X):
  """
  Inputs:
    X: numpy array of shape (n, f)
  Outputs:
    X_normd : numpy array of shape (n, f)
  """
  ### Write your code here
  min_max_scaler=preprocessing.MinMaxScaler()
  X_min_max=min_max_scaler.fit_transform(X)
  return X_min_max

In [ ]:
X=np.array([[1,-1,2],
           [2,0,0],
           [0,1,-1]])
normalize(X)

array([[0.5       , 0.        , 1.        ],
       [1.        , 0.5       , 0.33333333],
       [0.        , 1.        , 0.        ]])