<a href="https://colab.research.google.com/github/Aryamaan23/ML-TOOLBOX/blob/master/Copy_of_Copy_of_quizII_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Before you turn this problem in, make sure everything runs as expected. First, **Restart and Run All** (in the menubar in colab, select Runtime$\rightarrow$Restart and Run all) 

Make sure you only fill in any place that says `YOUR CODE HERE` and do not make any other changes to the code. If you add any code cells for your own testing. Please delete them before submission.

---

General Instructions:
- By array, I mean numpy array
- By matrix, I mean a numpy array of 2 dimensions

### 1
Given an array of ints length, return an array with the elements "rotated left" so {1, 2, 3} yields {2, 3, 1}.


rotate_left([1, 2, 3]) → [2, 3, 1] <br>
rotate_left([5, 11, 9]) → [11, 9, 5] <br>
rotate_left([7, 0, 0, 1]) → [0, 0, 1, 7] 

In [ ]:
import numpy as np
def rotate_left(num):
  """
  Inputs:
    num : numpy array 
  
  Outputs:
    num_rotated : numpy array
  """
  
  # YOUR CODE HERE
  temp = 0
  temp = num[0] # store the 1st no. in the array
    
  for i in range(len(num)):
    if i+1 < len(num):  # because when i = 2, arr[i+1] i.e. arr[3], which is invalid.
     num[i] = num[i+1]
    
  num[len(num)-1] = temp  # assign the temp variable to the last index
  num_rotated=num
  
  
  return num_rotated


In [ ]:
num = np.array([2, 4, 8, 2, 88, 3, 4])
np.all(rotate_left(num) == np.array([ 4,  8,  2, 88,  3,  4,  2]))
print('Test passed', '\U0001F44D')


Test passed 👍


In [ ]:
num = np.array([2, 4, 8, 2, 88, 3, 4])
rotate_left(num)


array([ 4,  8,  2, 88,  3,  4,  2])

In [ ]:
num=np.array([1,2,3])
rotate_left(num)

array([2, 3, 1])

### 2
Return the number of times that the string "code" appears anywhere in the given string, except we'll accept any letter for the 'd', so "cope" and "cooe" count.


count_code('aaacodebbb') → 1 <br>
count_code('codexxcode') → 2 <br>
count_code('cozexxcope') → 2

In [ ]:
import numpy as np
import re

def count_code(st):
  """
  Inputs:
      st: string
  Outputs:
      cnt: int, number of times 'code' appears in st according to the given specification in the question
  """
  
  # YOUR CODE HERE
  exp = '^co[a-z|A-Z]e$'
  cnt= 0
  for i in range(len(st) - 1):
    if re.match(exp, st[i:i + 4]):
      cnt = cnt + 1
  
  
  return cnt

In [ ]:
st = 'aaacodebbb'
assert count_code(st) == 1
print('Test passed', '\U0001F44D')


Test passed 👍


In [ ]:
st1='aaacodebbb'
count_code(st1)

1

In [ ]:
st2='codexxcode'
count_code(st2)

2

In [ ]:
st3='cozexxcope'
count_code(st3)

2

### 3
Most frequently occuring element in an array

Given an array, find the most frequent element in it. If there are multiple elements that appear maximum number of times, print any one of them.

Input : arr = [1, 3, 2, 1, 4, 1]
Output : 1

In [ ]:
def most_frequent(arr):
    """
    Inputs:
      arr : numpy array of ints

    Outputs:
      most_freq_el : int, most frequent element in array arr

    """  
    
    # YOUR CODE HERE
    most_freq_el=np.bincount(arr).argmax()
      
    
    
    return most_freq_el

In [ ]:
arr = [ 1, 5, 2, 1, 3, 2, 1]  
assert most_frequent(arr) == 1
print('Test passed', '\U0001F44D')


Test passed 👍


In [ ]:
arr=np.array([1,3,2,1,4,1])
most_frequent(arr)

1

In [ ]:
arr=np.array([1,2,2,2,3,4,5,6,7,7,7,7,8,8,8,8,8,8])
most_frequent(arr)

8

### 4
How to find all the local maxima (or peaks) in a 1d array?

Find all the peaks in a 1D numpy array a. Peaks are points surrounded by smaller values on both sides. First and last values of an array cannot be peaks

Input:

arr = [1, 3, 7, 1, 2, 6, 0, 1]

Desired Output: [2, 5]

In [ ]:
import numpy as np
from scipy.signal import argrelextrema

def local_maxima(arr):
    """
    Inputs:
        arr: numpy array
    Outputs:
        peak_inds : numpy array of indices of arr where peaks occur
    """
    
    # YOUR CODE HERE
    peak_inds=argrelextrema(arr,np.greater)
    return peak_inds

In [ ]:
arr=np.array([1,3,7,1,2,6,0,1])
local_maxima(arr)

(array([2, 5]),)

In [ ]:
assert np.all(local_maxima(np.array([1, 3, 7, 1, 2, 6, 0, 1])) == np.array([2, 5]))
print('Test passed', '\U0001F44D')


Test passed 👍


In [ ]:
x=np.array([2, 5])
print(x)

[2 5]


### 5
Compute the moving average of n elements of a numpy array <br>
Example:

array:  [8 8 3 7 7 0 4 2 5 2] <br>
moving average for n = 3 :  [ 6.33  6.    5.67  4.67  3.67  2.    3.67  3.  ]

In [ ]:
import numpy as np
def moving_avg(arr, n):
    """
    Inputs:
        arr: numpy array
        n : int, number of elements to consider while computing moving avg
    Outputs:
        moving_avg_arr : numpy array, contains moving avgs
    """
    
    # YOUR CODE HERE
    ret = np.cumsum(arr, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    moving_avg_arr=ret[n - 1:] / n
    return moving_avg_arr
    

In [ ]:
assert np.all(np.isclose(moving_avg(np.array([8, 8, 3, 7, 7, 0, 4, 2, 5, 2]), 3), np.array([6.33333333, 6. , 5.66666667, 4.66666667, 3.66666667, 2. , 3.66666667, 3.]), atol = 0.001))
print('Test passed', '\U0001F44D')


Test passed 👍


In [ ]:
arr=np.array([8,8,3,7,7,0,4,2,5,2])
n=3
moving_avg(arr,n)

array([6.33333333, 6.        , 5.66666667, 4.66666667, 3.66666667,
       2.        , 3.66666667, 3.        ])