<a href="https://colab.research.google.com/github/Aryamaan23/ML-TOOLBOX/blob/master/Copy_of_Quiz_3_(ML).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

General Instructions:
- By array, I mean numpy array
- By matrix, I mean a numpy array of 2 dimensions

### 1
Write a function to create and return an integer array of shape (5, 2) from a range between 100 to 200 (including 100, excluding 200) such that the difference between consecutive elements is 10.

In [ ]:
import numpy as np
def create_integer_array(a):
  a=np.array([[100,110],[120,130],[140,150],[160,170],[180,190]])
  return np.array(a)
create_integer_array(matrix)


array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

### 2
Given a numpy array ```a```, of shape ```(m, n)``` m>=3, n>=3. Write a function to return an array consisting of the elements in 3rd column of ```a``` <br>
Eg., Suppose
``` 
a = [[1 2 3]
     [4 5 6]
     [7 8 9]]    
```
Then 
```
column_3(a) -> [3 6 9]
```

In [ ]:
import numpy as np
def column_3(a):
  d=2
  r=[sub[d] for sub in a]
  return r
m=int(input())
n=int(input())
matrix=[]
for i in range(0,m):
  matrix+=[0]
for i in range(0,m):
  matrix[i]=[0]*n
for i in range(0,m):
  for j in range(0,n):
    matrix[i][j]=int(input())
s=np.array(matrix)
print(s)
a=column_3(matrix)
print(f'column_3(a) -> {a}')

3
3
1
2
3
4
5
6
7
8
9
[[1 2 3]
 [4 5 6]
 [7 8 9]]
column_3(a) -> [3, 6, 9]


### 3
Write a function which does the following. Given a numpy array $a$ of shape (m, n), index $i$ and an array $b$ of shape (m, ). Replace the $i_{th}$ column of $a$ with the array $b$  
Eg., Suppose
```
a = [[1 2 3]
     [4 5 6]
     [7 8 9]]
b = [30, 60, 90]

```    
Then,
```
replace_col(a, 2, b) -> [[1 2 30]
                         [4 5 60]
                         [7 8 90]]
```

In [ ]:
import numpy as np
def replace_col(a, i, b):
 x=a.copy()
 y=np.array(x)
 y[:,i]=np.array(b)
 return np.array(y)
m=int(input())
n=int(input())
matrix=[]
matrix2=[]
for i in range(0,m):
  matrix+=[0]
for i in range(0,m):
  matrix[i]=[0]*n
for i in range(0,m):
  for j in range(0,n):
    matrix[i][j]=int(input())
s=np.array(matrix)
print(s)
for i in range(0,1):
  matrix2+=[0]
for i in range(0,1):
  matrix2[i]=[0]*n
for i in range(0,1):
  for j in range(0,m):
    matrix2[i][j]=int(input())
z=np.array(matrix2)
print(z)
k=int(input())
replace_col(matrix,k,matrix2)

3
3
1
2
3
4
5
6
7
8
9
[[1 2 3]
 [4 5 6]
 [7 8 9]]
30
60
90
[[30 60 90]]
2


array([[ 1,  2, 30],
       [ 4,  5, 60],
       [ 7,  8, 90]])

### 4
Write a function which does the following. Given a numpy array $a$ of shape (m, n) and indices $i$, $j$. Return a numpy array which swaps the columns $i$ and $j$ of $a$
Eg., Suppose
```
a = [[1 2 3]
     [4 5 6]
     [7 8 9]]

swap_cols(a, 0, 2) -> [[3 2 1]
                       [6 5 4]
                       [9 8 7]]
```

In [ ]:
import numpy as np
def swap_cols(a, i, j):
  a[:,[i,j]]=a[:,[j,i]]
  return a
  
j=int(input())
k=int(input())
l=int(input())
ma=np.arange(j).reshape(k,l)
ik=int(input())
jk=int(input())
print(ma)
t=swap_cols(ma,ik,jk)
print()
print(f' {t}')
  


9
3
3
0
2
[[0 1 2]
 [3 4 5]
 [6 7 8]]

 [[2 1 0]
 [5 4 3]
 [8 7 6]]


## 5

There are various equivalent ways to define the determinant of a square matrix A, i.e. one with the same number of rows and columns. Perhaps the simplest way to express the determinant is by considering the elements in the top row and the respective minors; starting at the left, multiply the element by the minor, then subtract the product of the next element and its minor, and alternate adding and subtracting such products until all elements in the top row have been exhausted. For example, here is the result for a 4 × 4 matrix: <br>

<img src = "https://drive.google.com/uc?id=1TTljfFZAnOvqgAOiOrv6r4DDRROD-Vph"> <br>

Also, for a 2x2 matrix, this is the formula - <br>
<img src = "https://drive.google.com/uc?id=1H3aFpr1guevWjz4F-XRUQ9eP5TfjVLwu"> <br>

###5.1 Minor
Write a function that does the following. 
Given a square matrix $A$ and an index $i$, find and return the sub-matrix that is the minor corresponding to element at index $i$ of the first row of $A$

In [ ]:
def minor(A, i):
  return np.delete(np.delete(A,0,axis=0),i,axis=1)
j=int(input())
k=int(input())
l=int(input())
ma=np.arange(j).reshape(k,l)
print(ma)
ik=int(input())
minor(ma,ik)


9
3
3
[[0 1 2]
 [3 4 5]
 [6 7 8]]
1


array([[3, 5],
       [6, 8]])

###5.2
Given a square matrix $A$, write a function that computes and return the determinant using the formula given above and the helper function that you have defined called ```minor```. <br>
(Do not use the functions to compute determinant which numpy provides built in)

In [ ]:
import numpy as np
def determinant(A):
 n=len(A)
 temp=[0]*n
 total=1
 det=1

 for i in range(0,n):
   index=i

   while(A[index][i]==0 and index<n):
     index+=1
   if(index==n):
     continue
   if(index!=i):
     for j in range(0,n):
       A[index][j],A[i][j]=A[i][j],A[index][j]

     det=det*int(pow(-1,index-i))

   for j in range(0,n):
     temp[j]=A[i][j]

   for j in range(i+1,n):
     num1=temp[i]
     num2=A[j][i]

     for k in range(0,n):

       A[j][k]=(num1*A[j][k])-(num2*temp[k])
     total=total*num1

   for i in range(0,n):
     det=det*A[i][i]

   return int(det/total)


matrix=[]
m=int(input())
n=int(input())
for i in range(0,m):
  matrix+=[0]
for i in range(0,m):
  matrix[i]=[0]*n
for i in range(0,m):
  for j in range(0,n):
    matrix[i][j]=int(input())
print(matrix)
k=determinant(matrix)
print(f'Determinant is ->{k}')

3
3
1
2
3
2
1
2
0
0
2
[[1, 2, 3], [2, 1, 2], [0, 0, 2]]
Determinant is ->-6
